### ISSUE TITLE
ld: library not found for -lfreeimage

### ISSUE THREAD

**Issue by jdriselvato** [alvasnaedis/grit#1]
This is amazing that in 2016, there someone still supporting GRIT.. No less providing a make file to work with OSX. I'm trying to get this compiling on OS X but I'm have difficulty with installing free image. Do you  know of an easier way to get that installed?

**Comment by alvasnaedis** [comment]
@jdriselvato do you use (Homebrew)[http://brew.sh]? If so, it's only a matter of `brew install freeimage`!
I only got into GBA programming recently and found this tool, hope you can get it working too. 😊

**Comment by jdriselvato** [comment]
Perfect! That worked like a charm and I was able to compile GRIT. So it looks like if the compiling was successful, I should be able to use the command line version of GRIT. Does compiling also output the visual editor? Or is that a window exclusive.

**Comment by alvasnaedis** [comment]
@jdriselvato that one is Windows only, I'm afraid. Glad you got the rest working!

**Comment by jdriselvato** [comment]
Awesome, well I appreciate your time and swift responses. I've linked this repo in my learning document: https://github.com/jdriselvato/NDS-Development/tree/master/tools

I look forward to seeing what you develop on the GBA :dart:
